macro(add_ros2 target link)
    find_package(rclcpp REQUIRED)
    find_package(std_msgs REQUIRED)
    find_package(sensor_msgs REQUIRED)
    ament_target_dependencies(${target} ${link} rclcpp std_msgs sensor_msgs)
    message_link_information(${target} ${link} ROS2)
endmacro()

macro(add_zed target link)
    find_package(ZED REQUIRED)
    target_link_libraries(${target} ${link} ${ZED_LIBRARIES})
    target_include_directories(${target} ${link} ${ZED_INCLUDE_DIRS})
    message_link_information(${target} ${link} ZED2)
endmacro()

macro(add_k4a target link)
    find_package(k4a REQUIRED)
    target_link_libraries(${target} ${link} k4a)
    message_link_information(${target} ${link} k4a)
endmacro()